"use client";
import { useState } from "react";
const quotes = [
  { text: "Neural's approach made a technically complex project feel simple. Every stage was strategic, well communicated, and executed with a balance of creativity and engineering detail.", name: "Sarah Matthews", role: "Product Director" },
  { text: "The team transformed our early idea into a polished product. Their speed, clarity, and attention to the user experience made Neural an invaluable technology partner.", name: "Alexandra Reed", role: "Founder, Lumina" },
  { text: "From product strategy through launch, Neural consistently found practical solutions. We gained a faster platform and a much clearer digital experience for our customers.", name: "Michael Turner", role: "Operations Lead" },
  { text: "Communication was direct and the engineering quality was excellent. The final experience feels modern, focused, and ready to support the next stage of our growth.", name: "Emily Collins", role: "Product Manager" },
];
export default function Testimonials() {
  const [active, setActive] = useState(0); const quote = quotes[active]; const move = (direction: number) => setActive((active + direction + quotes.length) % quotes.length);
  return <><section className="testimonials section-pad"><div className="testimonial-summary"><p className="kicker">Our testimonials</p><h2>The impact of our AI solutions</h2><strong>269+</strong><div className="rating">★★★★★ <span>4.9 average rating</span></div></div><article className="quote-card"><div className="quote-nav"><button onClick={() => move(-1)} aria-label="Previous testimonial">←</button><button onClick={() => move(1)} aria-label="Next testimonial">→</button></div><p key={active} className="quote-text">“{quote.text}”</p><div className="quote-author"><span>{quote.name.split(" ").map((part) => part[0]).join("")}</span><div><b>{quote.name}</b><small>{quote.role}</small></div></div></article></section><section id="insights" className="insights section-pad"><div className="section-head"><div><p className="kicker">Blogs & news</p><h2>Insights & stories</h2></div><a className="text-link" href="#contact">Explore more <span>↗</span></a></div><div className="blog-grid"><article><div className="blog-art art-one"><i /></div><p>Artificial intelligence · 5 min</p><h3>How AI is shaping the future of digital products</h3></article><article><div className="blog-art art-two"><i /></div><p>Product design · 6 min</p><h3>Why every modern brand needs an AI strategy</h3></article><article><div className="blog-art art-three"><i /></div><p>Engineering · 4 min</p><h3>Building software that stays useful as you grow</h3></article></div></section></>;
}
