import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import WhatsAppFloatingButton from "@/components/WhatsAppFloatingButton";
import { getPostBySlug } from "@/lib/posts";
import { getWhatsAppLink, siteConfig } from "@/lib/site-config";

type Props = { params: { slug: string } };
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const post = await getPostBySlug(params.slug); if (!post) return { title: "Article not found", robots: { index: false, follow: false } }; const url = `/blog/${post.slug}`;
  return { title: post.title, description: post.description, keywords: post.keywords, alternates: { canonical: url }, openGraph: { type: "article", url, title: post.title, description: post.description, publishedTime: post.publishedAt, modifiedTime: post.updatedAt, authors: [siteConfig.name], tags: post.keywords, images: ["/og-image.png"] }, twitter: { card: "summary_large_image", title: post.title, description: post.description, images: ["/og-image.png"] } };
}
export default async function PostPage({ params }: Props) {
  const post = await getPostBySlug(params.slug); if (!post) notFound(); const articleUrl = `${siteConfig.url}/blog/${post.slug}`;
  const jsonLd = { "@context": "https://schema.org", "@graph": [{ "@type": "Article", "@id": `${articleUrl}#article`, headline: post.title, description: post.description, datePublished: post.publishedAt, dateModified: post.updatedAt, mainEntityOfPage: articleUrl, inLanguage: "en", keywords: post.keywords.join(", "), author: { "@type": "Organization", "@id": `${siteConfig.url}/#organization`, name: siteConfig.name }, publisher: { "@id": `${siteConfig.url}/#organization` }, image: `${siteConfig.url}/og-image.png`, articleSection: post.category }, { "@type": "FAQPage", "@id": `${articleUrl}#faq`, mainEntity: post.faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }] };
  return <><Header /><main className="article-page"><article><header className="article-hero"><div className="article-breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/blog">Insights</Link><span>/</span><span>{post.category}</span></div><div className="article-labels"><span>{post.kind === "news" ? "Industry update" : post.category}</span><span>{post.readingMinutes} min read</span></div><h1>{post.title}</h1><p className="article-lede">{post.description}</p><div className="article-byline"><span className="article-avatar">N</span><div><b>{siteConfig.name}</b><small>{new Date(post.publishedAt).toLocaleDateString("en", { month: "long", day: "numeric", year: "numeric" })} · AI-assisted editorial</small></div></div></header><div className="article-layout"><aside><p>In this article</p><nav>{post.sections.map((section, index) => <a key={section.heading} href={`#section-${index + 1}`}>{section.heading}</a>)}</nav><div className="article-note">Use this article as practical guidance. Validate legal, financial, security, and business-critical decisions with qualified professionals.</div></aside><div className="article-content">{post.sections.map((section, index) => <section id={`section-${index + 1}`} key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph, paragraphIndex) => <p key={paragraphIndex}>{paragraph}</p>)}</section>)}<section className="article-faq"><p className="kicker">Common questions</p><h2>Frequently asked questions</h2>{post.faq.map((item) => <details key={item.question}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</section><section className="article-cta"><p className="kicker">Work with Neural</p><h2>{post.ctaTitle}</h2><p>{post.ctaText}</p><div><a className="pill pill-lime" href={getWhatsAppLink(`Hi, I read "${post.title}" and would like to discuss a project.`)} target="_blank" rel="noopener noreferrer" data-google-ads-conversion>WhatsApp <span>↗</span></a><a className="pill pill-fiverr" href={siteConfig.fiverrUrl} target="_blank" rel="noopener noreferrer" data-google-ads-conversion>Hire us on Fiverr <span>↗</span></a></div></section></div></div></article><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /></main><Footer /><WhatsAppFloatingButton /></>;
}
